/* Compact Node Registry - 25 node types */
type E={l:string;i:string;c:string;g:string;w:string;x:string;d:any;n:{n:string;l:string;t:string;r?:1;d?:any;o?:{l:string;v:string}[]}[];o:{n:string;l:string;t:string}[]};
export const M:Record<string,E>={
qwenImageGen:{l:'A图像-Qwen生成',i:'🖼️',c:'#6366f1',g:'image',w:'qwen-gen',x:'CLIPTextEncode',d:{prompt:'',negative_prompt:'',width:1024,height:1024},n:[{n:'prompt',l:'提示词',t:'text',r:1},{n:'negative_prompt',l:'负面提示词',t:'text'},{n:'width',l:'宽',t:'number',d:1024},{n:'height',l:'高',t:'number',d:1024}],o:[{n:'image',l:'图片',t:'image'}]},
qwenImageEdit:{l:'B图像-Qwen编辑',i:'✏',c:'#818cf8',g:'image',w:'qwen-edit',x:'CUSTOM_QWEN_EDIT',d:{prompt:'',strength:0.7},n:[{n:'image',l:'输入图片',t:'image',r:1},{n:'prompt',l:'编辑指令',t:'text',r:1},{n:'strength',l:'编辑强度',t:'number',d:0.7}],o:[{n:'image',l:'图片',t:'image'}]},
zimageGen:{l:'C图像-Zimage',i:'⚡',c:'#a855f7',g:'image',w:'Z-image-Nunchaku加速文生图',x:'NunchakuZImageDiTLoader',d:{prompt:'',width:768,height:1136,steps:15,cfg:1.5,seed:-1},n:[{n:'prompt',l:'提示词',t:'text',r:1},{n:'width',l:'宽',t:'number',d:768},{n:'height',l:'高',t:'number',d:1136},{n:'steps',l:'步数',t:'number',d:15},{n:'cfg',l:'CFG',t:'number',d:1.5},{n:'seed',l:'种子',t:'number',d:-1}],o:[{n:'image',l:'图片',t:'image'}]},
fluxImageGen:{l:'D图像-流',i:'🌊',c:'#06b6d4',g:'image',w:'flux-gen',x:'CUSTOM_FLUX_GEN',d:{prompt:'',width:1024,height:1024,guidance:3.5},n:[{n:'prompt',l:'提示词',t:'text',r:1},{n:'width',l:'宽',t:'number',d:1024},{n:'height',l:'高',t:'number',d:1024},{n:'guidance',l:'引导',t:'number',d:3.5}],o:[{n:'image',l:'图片',t:'image'}]},
sdxlIL:{l:'E图像-SDXL-IL',i:'🎯',c:'#ec4899',g:'image',w:'sdxl-il',x:'CUSTOM_SDXL_IL',d:{prompt:'',strength:0.7},n:[{n:'image',l:'输入图片',t:'image',r:1},{n:'prompt',l:'提示词',t:'text'},{n:'strength',l:'强度',t:'number',d:0.7}],o:[{n:'image',l:'图片',t:'image'}]},
fireRedEdit:{l:'F图像-FireRed编辑',i:'🔥',c:'#f97316',g:'image',w:'firered-edit',x:'CUSTOM_FIRERED_EDIT',d:{prompt:''},n:[{n:'image',l:'输入图片',t:'image',r:1},{n:'prompt',l:'编辑指令',t:'text',r:1},{n:'mask',l:'蒙版',t:'image'}],o:[{n:'image',l:'图片',t:'image'}]},
wanVideoGen:{l:'G视频-Wan图生',i:'🎬',c:'#22c55e',g:'video',w:'wan-video',x:'CUSTOM_WAN_VIDEO',d:{prompt:'',duration:5,fps:16},n:[{n:'image',l:'起始图片',t:'image',r:1},{n:'prompt',l:'视频描述',t:'text',r:1},{n:'duration',l:'时长(秒)',t:'number',d:5},{n:'fps',l:'帧率',t:'number',d:16}],o:[{n:'video',l:'视频',t:'video'}]},
ltxVideoGen:{l:'H视频-LTX',i:'🎥',c:'#10b981',g:'video',w:'ltx-video',x:'CUSTOM_LTX_VIDEO',d:{prompt:'',duration:5,width:768,height:512},n:[{n:'prompt',l:'视频描述',t:'text',r:1},{n:'duration',l:'时长',t:'number',d:5},{n:'width',l:'宽',t:'number',d:768},{n:'height',l:'高',t:'number',d:512}],o:[{n:'video',l:'视频',t:'video'}]},
lipSyncHuman:{l:'J视频-对口型数字人',i:'👄',c:'#eab308',g:'video',w:'lipsync',x:'CUSTOM_LIPSYNC',d:{text:''},n:[{n:'image',l:'人物图片',t:'image',r:1},{n:'audio',l:'音频文件',t:'image',r:1},{n:'text',l:'口播文本',t:'text'}],o:[{n:'video',l:'视频',t:'video'}]},
personReplace:{l:'K视频-人物替换',i:'👤',c:'#ef4444',g:'video',w:'person-replace',x:'CUSTOM_PERSON_REPLACE',d:{strength:0.8},n:[{n:'target_image',l:'目标图片',t:'image',r:1},{n:'source_face',l:'人物面部',t:'image',r:1},{n:'strength',l:'替换强度',t:'number',d:0.8}],o:[{n:'image',l:'图片',t:'image'}]},
gaussianSplat:{l:'L视角-高斯泼溅',i:'🔮',c:'#8b5cf6',g:'3d',w:'gaussian',x:'CUSTOM_GAUSSIAN_SPLAT',d:{quality:'high'},n:[{n:'images',l:'多视角图片',t:'image',r:1},{n:'quality',l:'质量',t:'select',d:'high',o:[{l:'高',v:'high'},{l:'中',v:'medium'}]}],o:[{n:'image',l:'3D场景',t:'image'}]},
upscaleWatermark:{l:'M高清放大去水印',i:'🔍',c:'#14b8a6',g:'image',w:'upscale',x:'UltimateSDUpscale',d:{scale:4,remove_watermark:'true'},n:[{n:'image',l:'输入图片',t:'image',r:1},{n:'scale',l:'放大倍数',t:'number',d:4},{n:'remove_watermark',l:'去水印',t:'select',d:'true',o:[{l:'是',v:'true'},{l:'否',v:'false'}]}],o:[{n:'image',l:'图片',t:'image'}]},
};