/* Compact Node Registry Part 2 - remaining 12 node types */
type E={l:string;i:string;c:string;g:string;w:string;x:string;d:any;n:{n:string;l:string;t:string;r?:1;d?:any;o?:{l:string;v:string}[]}[];o:{n:string;l:string;t:string}[]};
export const M2:Record<string,E>={
storyboardPrompt:{l:'剧情分镜提示词',i:'🎞️',c:'#0ea5e9',g:'tool',w:'local-storyboard',x:'LOCAL_STORYBOARD',d:{script:'',customRequirements:'',segmentCount:3,segmentRule:'每段 5 秒',totalDuration:15,inheritPrevious:'true',effects:'',systemPrompt:''},n:[{n:'script',l:'剧本/剧情',t:'text',r:1},{n:'customRequirements',l:'专业修改输入',t:'text'},{n:'segmentCount',l:'分镜数量',t:'number',r:1,d:3},{n:'segmentRule',l:'分段规则',t:'text',r:1,d:'每段 5 秒'},{n:'totalDuration',l:'总时长(秒)',t:'number',r:1,d:15},{n:'inheritPrevious',l:'首帧承接上一段尾帧',t:'select',r:1,d:'true',o:[{l:'是',v:'true'},{l:'否',v:'false'}]},{n:'effects',l:'专业效果',t:'text'},{n:'systemPrompt',l:'整体分析提示词',t:'text'}],o:[{n:'storyboard_list',l:'完整分镜列表',t:'text'},{n:'error_warning',l:'错误/警告',t:'text'}]},
cinematographyKnowledge:{l:'影视专业效果知识库',i:'🎥',c:'#f59e0b',g:'tool',w:'local-knowledge',x:'LOCAL_KNOWLEDGE',d:{selectedEffectIds:[],customTerms:[],presetName:''},n:[{n:'customTerms',l:'自定义术语',t:'text'}],o:[{n:'promptText',l:'专业效果',t:'text'}]},
audioGen:{l:'N声音生成-音乐-声音克隆',i:'🎵',c:'#f59e0b',g:'audio',w:'audio-gen',x:'CUSTOM_AUDIO_GEN',d:{prompt:'',duration:30},n:[{n:'prompt',l:'音乐描述',t:'text',r:1},{n:'duration',l:'时长(秒)',t:'number',d:30},{n:'reference_audio',l:'参考音频',t:'image'}],o:[{n:'audio',l:'音频',t:'audio'}]},
motionTransfer:{l:'P视频-动作迁移',i:'🏃',c:'#d946ef',g:'video',w:'motion',x:'CUSTOM_MOTION_TRANSFER',d:{},n:[{n:'source_video',l:'源视频(动作)',t:'image',r:1},{n:'target_image',l:'目标人物',t:'image',r:1}],o:[{n:'video',l:'视频',t:'video'}]},
storyboardGPT:{l:'Q分镜图gptimage-banana2',i:'📋',c:'#0ea5e9',g:'image',w:'storyboard',x:'CUSTOM_STORYBOARD',d:{script:'',style:'anime',num_frames:4},n:[{n:'script',l:'分镜脚本',t:'text',r:1},{n:'style',l:'风格',t:'select',d:'anime',o:[{l:'动漫',v:'anime'},{l:'写实',v:'realistic'},{l:'电影',v:'cinematic'}]},{n:'num_frames',l:'帧数',t:'number',d:4}],o:[{n:'image',l:'分镜图',t:'image'}]},
intentImage:{l:'R图像-表意图',i:'💡',c:'#84cc16',g:'image',w:'intent',x:'CUSTOM_INTENT_IMAGE',d:{prompt:'',style:'clean'},n:[{n:'prompt',l:'意图描述',t:'text',r:1},{n:'style',l:'风格',t:'select',d:'clean',o:[{l:'简洁',v:'clean'},{l:'详细',v:'detailed'}]}],o:[{n:'image',l:'表意图',t:'image'}]},
booguImage:{l:'S图像-Boogu',i:'B',c:'#f472b6',g:'image',w:'boogu',x:'CUSTOM_BOOGU',d:{prompt:'',width:1024,height:1024},n:[{n:'prompt',l:'提示词',t:'text',r:1},{n:'width',l:'宽',t:'number',d:1024},{n:'height',l:'高',t:'number',d:1024}],o:[{n:'image',l:'图片',t:'image'}]},
kreaImage:{l:'T图像-Krea',i:'🎨',c:'#fb923c',g:'image',w:'krea',x:'CUSTOM_KREA',d:{prompt:'',style:'photographic',width:1024,height:1024},n:[{n:'prompt',l:'提示词',t:'text',r:1},{n:'style',l:'风格',t:'select',d:'photographic',o:[{l:'摄影',v:'photographic'},{l:'插画',v:'illustration'},{l:'3D',v:'3d'}]},{n:'width',l:'宽',t:'number',d:1024},{n:'height',l:'高',t:'number',d:1024}],o:[{n:'image',l:'图片',t:'image'}]},
universalMaker:{l:'Y通用制作',i:'🔧',c:'#6b7280',g:'tool',w:'universal',x:'CUSTOM_UNIVERSAL',d:{type:'image',prompt:''},n:[{n:'type',l:'制作类型',t:'select',r:1,d:'image',o:[{l:'图片',v:'image'},{l:'视频',v:'video'},{l:'音频',v:'audio'}]},{n:'prompt',l:'描述',t:'text',r:1},{n:'reference',l:'参考文件',t:'image'}],o:[{n:'image',l:'输出',t:'image'}]},
toolSettings:{l:'Z工具设置',i:'⚙',c:'var(--theme-muted)',g:'tool',w:'settings',x:'CUSTOM_TOOL_SETTINGS',d:{output_format:'png',quality:95,batch_count:1},n:[{n:'output_format',l:'输出格式',t:'select',d:'png',o:[{l:'PNG',v:'png'},{l:'JPG',v:'jpg'},{l:'MP4',v:'mp4'}]},{n:'quality',l:'质量',t:'number',d:95},{n:'batch_count',l:'批量',t:'number',d:1}],o:[]},
joyAIEcho:{l:'JoyAI-Echo多镜头视频音频',i:'🎭',c:'#c084fc',g:'video',w:'joyai-echo',x:'CUSTOM_JOYAI_ECHO',d:{script:'',num_shots:3,duration_per_shot:5,style:'cinematic'},n:[{n:'script',l:'剧本/描述',t:'text',r:1},{n:'num_shots',l:'镜头数',t:'number',d:3},{n:'duration_per_shot',l:'每镜头时长',t:'number',d:5},{n:'style',l:'风格',t:'select',d:'cinematic',o:[{l:'电影',v:'cinematic'},{l:'动漫',v:'anime'}]}],o:[{n:'video',l:'视频',t:'video'}]},
refMultiFusion:{l:'参考图-多图融合',i:'🔄',c:'#ec4899',g:'ref',w:'ref-fusion',x:'IPAdapterApply',d:{fusion_strength:0.5},n:[{n:'image1',l:'图片1',t:'image',r:1},{n:'image2',l:'图片2',t:'image',r:1},{n:'fusion_strength',l:'融合强度',t:'number',d:0.5}],o:[{n:'image',l:'融合图',t:'image'}]},
refWashImage:{l:'参考图-洗图',i:'🖌',c:'#f43f5e',g:'ref',w:'ref-wash',x:'IPAdapterApply',d:{strength:0.6},n:[{n:'image',l:'输入图片',t:'image',r:1},{n:'style_ref',l:'风格参考图',t:'image',r:1},{n:'strength',l:'风格强度',t:'number',d:0.6}],o:[{n:'image',l:'图片',t:'image'}]},
refImageClear:{l:'参考图-图片变清晰',i:'✨',c:'#22c55e',g:'ref',w:'ref-clear',x:'UltimateSDUpscale',d:{scale:2},n:[{n:'image',l:'模糊图片',t:'image',r:1},{n:'scale',l:'增强倍数',t:'number',d:2}],o:[{n:'image',l:'清晰图',t:'image'}]},
refImageToVideo:{l:'参考图-图生视频',i:'📹',c:'#3b82f6',g:'ref',w:'ref-img2vid',x:'CUSTOM_REF_IMG2VID',d:{prompt:'',duration:5},n:[{n:'image',l:'参考图片',t:'image',r:1},{n:'prompt',l:'动作描述',t:'text',r:1},{n:'duration',l:'时长(秒)',t:'number',d:5}],o:[{n:'video',l:'视频',t:'video'}]},
};