import { useSettingsStore } from '@/stores/settingsStore';

export const DEFAULT_STORYBOARD_SYSTEM_PROMPT = '你是专业影视分镜师、摄影指导和视频提示词设计师。请根据剧情、参考人物/场景图片及其备注，按指定片段数和总时长生成连续分镜。严格返回约定 JSON。每段输出首帧生图提示词、尾帧生图提示词、首尾帧视频提示词，以及一句符合人物身份和剧情的台词（dialogue，口语化，用于配音）。保持人物身份、服装、场景空间和光线连续；不得把未出现的人物或场景写入当前图片提示词。';
export interface StoryboardSegment { segmentId:string; duration:number; firstFrame:{prompt:string;inheritsPreviousLastFrame:boolean}; lastFrame:{prompt:string}; videoPrompt:string; characters:string[]; locations:string[]; continuity:string; negativePrompt:string; dialogue:string; }
export interface StoryboardResult { segments:StoryboardSegment[]; warnings:string[]; }
function endpoint(provider:string, base:string, model = useSettingsStore.getState().optimizerModel) { const b=base.replace(/\/+$/,''); if(provider==='gemini') return b.includes('/models/')?b:`${b}/models/${encodeURIComponent(model)}:generateContent`; if(provider==='ollama') return b.endsWith('/generate')?b:`${b}/api/generate`; if(provider==='anthropic') return b.endsWith('/messages')?b:`${b}/messages`; return b.endsWith('/chat/completions')?b:`${b}/chat/completions`; }
function parse(raw:string): StoryboardResult { const cleaned=raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim(); const value=JSON.parse(cleaned); const segments=Array.isArray(value)?value:value.segments; if(!Array.isArray(segments)) throw new Error('AI 返回缺少 segments 数组'); return { segments:segments.map((s:any,i)=>({segmentId:String(s.segmentId||`segment_${String(i+1).padStart(2,'0')}`),duration:Number(s.duration)||0,firstFrame:{prompt:String(s.firstFrame?.prompt||''),inheritsPreviousLastFrame:Boolean(s.firstFrame?.inheritsPreviousLastFrame)},lastFrame:{prompt:String(s.lastFrame?.prompt||'')},videoPrompt:String(s.videoPrompt||''),characters:Array.isArray(s.characters)?s.characters.map(String):[],locations:Array.isArray(s.locations)?s.locations.map(String):[],continuity:String(s.continuity||''),negativePrompt:String(s.negativePrompt||''),dialogue:String(s.dialogue||'')})),warnings:Array.isArray(value.warnings)?value.warnings.map(String):[]}; }
export async function generateStoryboard(input:{script:string;segmentCount:number;segmentRule:string;totalDuration:number;characterNotes:string;sceneNotes:string;effects:string;customRequirements:string;inheritPrevious:boolean;systemPrompt?:string;imageContext?:string[]}, signal?:AbortSignal, overrides?:{provider?:string;baseUrl?:string;apiKey?:string;model?:string}):Promise<StoryboardResult> {
  const s=useSettingsStore.getState();
  // 未配置「分镜 AI（提示词 AI）」时，自动回退到付费 API 的聊天 AI 配置
  // 优先级：调用方 overrides（短剧工作室独立分镜 AI 配置） > 提示词 AI > 聊天 AI 回退
  const useChatFallback = !s.optimizerApiKey && s.optimizerProvider !== 'ollama' && (!!s.chatApiKey || s.chatProvider === 'ollama');
  const provider = overrides?.provider || (useChatFallback ? s.chatProvider : s.optimizerProvider);
  const apiKey = overrides?.apiKey || (useChatFallback ? s.chatApiKey : s.optimizerApiKey);
  const baseUrl = overrides?.baseUrl || (useChatFallback ? s.chatBaseUrl : s.optimizerBaseUrl);
  const model = overrides?.model || (useChatFallback ? s.chatModel : s.optimizerModel);
  if (!apiKey && provider !== 'ollama') throw new Error('请先配置分镜 AI API 密钥（短剧工作室 → 分镜 AI 设置，或在设置 → 提示词 AI 中配置，将自动回退聊天 AI）');
  if(!input.script.trim()) throw new Error('剧情/剧本不能为空'); if(input.segmentCount<1||input.segmentCount>100) throw new Error('片段数量必须为 1-100'); if(input.totalDuration<=0) throw new Error('总时长必须大于 0 秒');
  const requestId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`; const schema='{"segments":[{"segmentId":"segment_01","duration":5,"firstFrame":{"prompt":"","inheritsPreviousLastFrame":false},"lastFrame":{"prompt":""},"videoPrompt":"","characters":[],"locations":[],"continuity":"","negativePrompt":"","dialogue":""}],"warnings":[]}';
  const user=`requestId: ${requestId}\n剧情：${input.script}\n片段数量：${input.segmentCount}\n分段规则：${input.segmentRule}\n总时长（秒）：${input.totalDuration}\n首帧承接上一段尾帧：${input.inheritPrevious}\n人物参考及备注：${input.characterNotes||'无'}\n场景参考及备注：${input.sceneNotes||'无'}\n专业效果：${input.effects||'无'}\n自定义要求：${input.customRequirements||'无'}\n重要：firstFrame.prompt、lastFrame.prompt、videoPrompt 必须先用中文生成；dialogue 直接写中文台词（配音用），每段一句。客户端会在用户确认后单独翻译成英文。只返回 JSON，结构示例：${schema}`;
  const systemPrompt=input.systemPrompt||s.storyboardSystemPrompt||DEFAULT_STORYBOARD_SYSTEM_PROMPT;
  const imageUrls=(input.imageContext||[]).filter(url=>/^https?:\/\//i.test(url)||/^data:image\//i.test(url));
  const headers:Record<string,string>={'Content-Type':'application/json'}; if(provider==='anthropic'){headers['x-api-key']=apiKey;headers['anthropic-version']='2023-06-01';}else if(provider==='gemini'){if(apiKey)headers['x-goog-api-key']=apiKey;}else if(provider!=='ollama')headers.Authorization=`Bearer ${apiKey}`;
  const openAiContent=[{type:'text',text:user},...imageUrls.map(url=>({type:'image_url',image_url:{url}}))];
  const body=provider==='gemini'?{contents:[{role:'user',parts:[{text:`${systemPrompt}\n${user}`},...imageUrls.map(url=>url.startsWith('data:image/')?{inline_data:{mime_type:url.slice(5,url.indexOf(';')),data:url.split(',')[1]}}:{text:`参考图 URL：${url}`})]}],generationConfig:{temperature:0.25}}:provider==='anthropic'?{model:model,max_tokens:4000,temperature:0.25,system:systemPrompt,messages:[{role:'user',content:openAiContent}]}:provider==='ollama'?{model:model,stream:false,system:systemPrompt,prompt:user,images:imageUrls.filter(url=>url.startsWith('data:image/')).map(url=>url.split(',')[1])}:{model:model,temperature:0.25,response_format:{type:'json_object'},messages:[{role:'system',content:systemPrompt},{role:'user',content:imageUrls.length?openAiContent:user}]};
  const response=await fetch(endpoint(provider,baseUrl,model),{method:'POST',headers,body:JSON.stringify(body),signal}); const data:any=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error?.message||data.message||`分镜 AI 请求失败（HTTP ${response.status}）`); const text= provider==='ollama'?data.response:data.choices?.[0]?.message?.content; if(typeof text!=='string') throw new Error('分镜 AI 没有返回文本');
  try{return parse(text);}catch{ const repair=`请修复下面内容为合法 JSON，只返回 JSON，不添加解释。必须符合：${schema}\n原始内容：${text}`; const repairBody=provider==='gemini'?{contents:[{parts:[{text:repair}]}]}:provider==='anthropic'?{model:model,max_tokens:4000,system:'你是 JSON 修复器，只输出合法 JSON。',messages:[{role:'user',content:repair}]}:provider==='ollama'?{model:model,stream:false,prompt:repair}:{model:model,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:'你是 JSON 修复器，只输出合法 JSON。'},{role:'user',content:repair}]}; const repairResponse=await fetch(endpoint(provider,baseUrl,model),{method:'POST',headers,body:JSON.stringify(repairBody),signal}); const repaired:any=await repairResponse.json().catch(()=>({})); const repairedText=provider==='ollama'?repaired.response:provider==='gemini'?repaired.candidates?.[0]?.content?.parts?.[0]?.text:provider==='anthropic'?repaired.content?.[0]?.text:repaired.choices?.[0]?.message?.content; if(typeof repairedText!=='string')throw new Error('AI 返回不是合法 JSON，修复失败'); try{return parse(repairedText);}catch{throw new Error('AI 返回不是合法分镜 JSON');} }
}