import { useSettingsStore } from '@/stores/settingsStore';

export const DEFAULT_STORYBOARD_SYSTEM_PROMPT = '你是专业影视分镜师、摄影指导和视频提示词设计师。请根据剧情、参考人物/场景图片及其备注，按指定片段数和总时长生成连续分镜。严格返回约定 JSON。每段输出首帧生图提示词、尾帧生图提示词和首尾帧视频提示词。保持人物身份、服装、场景空间和光线连续；不得把未出现的人物或场景写入当前图片提示词。';
export interface StoryboardSegment { segmentId:string; duration:number; firstFrame:{prompt:string;inheritsPreviousLastFrame:boolean}; lastFrame:{prompt:string}; videoPrompt:string; characters:string[]; locations:string[]; continuity:string; negativePrompt:string; }
export interface StoryboardResult { segments:StoryboardSegment[]; warnings:string[]; }
function endpoint(provider:string, base:string) { const b=base.replace(/\/+$/,''); if(provider==='gemini') return b.includes('/models/')?b:`${b}/models/${encodeURIComponent(useSettingsStore.getState().optimizerModel)}:generateContent`; if(provider==='ollama') return b.endsWith('/generate')?b:`${b}/api/generate`; if(provider==='anthropic') return b.endsWith('/messages')?b:`${b}/messages`; return b.endsWith('/chat/completions')?b:`${b}/chat/completions`; }
function parse(raw:string): StoryboardResult { const cleaned=raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim(); const value=JSON.parse(cleaned); const segments=Array.isArray(value)?value:value.segments; if(!Array.isArray(segments)) throw new Error('AI 返回缺少 segments 数组'); return { segments:segments.map((s:any,i)=>({segmentId:String(s.segmentId||`segment_${String(i+1).padStart(2,'0')}`),duration:Number(s.duration)||0,firstFrame:{prompt:String(s.firstFrame?.prompt||''),inheritsPreviousLastFrame:Boolean(s.firstFrame?.inheritsPreviousLastFrame)},lastFrame:{prompt:String(s.lastFrame?.prompt||'')},videoPrompt:String(s.videoPrompt||''),characters:Array.isArray(s.characters)?s.characters.map(String):[],locations:Array.isArray(s.locations)?s.locations.map(String):[],continuity:String(s.continuity||''),negativePrompt:String(s.negativePrompt||'')})),warnings:Array.isArray(value.warnings)?value.warnings.map(String):[]}; }
export async function generateStoryboard(input:{script:string;segmentCount:number;segmentRule:string;totalDuration:number;characterNotes:string;sceneNotes:string;effects:string;customRequirements:string;inheritPrevious:boolean;systemPrompt?:string;imageContext?:string[]}, signal?:AbortSignal):Promise<StoryboardResult> {
  const s=useSettingsStore.getState(); if(!s.optimizerApiKey&&s.optimizerProvider!=='ollama') throw new Error('请先在设置中填写分镜 AI API 密钥');
  if(!input.script.trim()) throw new Error('剧情/剧本不能为空'); if(input.segmentCount<1||input.segmentCount>100) throw new Error('片段数量必须为 1-100'); if(input.totalDuration<=0) throw new Error('总时长必须大于 0 秒');
  const requestId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`; const schema='{"segments":[{"segmentId":"segment_01","duration":5,"firstFrame":{"prompt":"","inheritsPreviousLastFrame":false},"lastFrame":{"prompt":""},"videoPrompt":"","characters":[],"locations":[],"continuity":"","negativePrompt":""}],"warnings":[]}';
  const user=`requestId: ${requestId}\n剧情：${input.script}\n片段数量：${input.segmentCount}\n分段规则：${input.segmentRule}\n总时长（秒）：${input.totalDuration}\n首帧承接上一段尾帧：${input.inheritPrevious}\n人物参考及备注：${input.characterNotes||'无'}\n场景参考及备注：${input.sceneNotes||'无'}\n专业效果：${input.effects||'无'}\n自定义要求：${input.customRequirements||'无'}\n重要：firstFrame.prompt、lastFrame.prompt、videoPrompt 必须先用中文生成，客户端会在用户确认后单独翻译成英文。只返回 JSON，结构示例：${schema}`;
  const systemPrompt=input.systemPrompt||s.storyboardSystemPrompt||DEFAULT_STORYBOARD_SYSTEM_PROMPT;
  const imageUrls=(input.imageContext||[]).filter(url=>/^https?:\/\//i.test(url)||/^data:image\//i.test(url));
  const headers:Record<string,string>={'Content-Type':'application/json'}; if(s.optimizerProvider==='anthropic'){headers['x-api-key']=s.optimizerApiKey;headers['anthropic-version']='2023-06-01';}else if(s.optimizerProvider==='gemini'){if(s.optimizerApiKey)headers['x-goog-api-key']=s.optimizerApiKey;}else if(s.optimizerProvider!=='ollama')headers.Authorization=`Bearer ${s.optimizerApiKey}`;
  const openAiContent=[{type:'text',text:user},...imageUrls.map(url=>({type:'image_url',image_url:{url}}))];
  const body=s.optimizerProvider==='gemini'?{contents:[{role:'user',parts:[{text:`${systemPrompt}\n${user}`},...imageUrls.map(url=>url.startsWith('data:image/')?{inline_data:{mime_type:url.slice(5,url.indexOf(';')),data:url.split(',')[1]}}:{text:`参考图 URL：${url}`})]}],generationConfig:{temperature:0.25}}:s.optimizerProvider==='anthropic'?{model:s.optimizerModel,max_tokens:4000,temperature:0.25,system:systemPrompt,messages:[{role:'user',content:openAiContent}]}:s.optimizerProvider==='ollama'?{model:s.optimizerModel,stream:false,system:systemPrompt,prompt:user,images:imageUrls.filter(url=>url.startsWith('data:image/')).map(url=>url.split(',')[1])}:{model:s.optimizerModel,temperature:0.25,response_format:{type:'json_object'},messages:[{role:'system',content:systemPrompt},{role:'user',content:imageUrls.length?openAiContent:user}]};
  const response=await fetch(endpoint(s.optimizerProvider,s.optimizerBaseUrl),{method:'POST',headers,body:JSON.stringify(body),signal}); const data:any=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error?.message||data.message||`分镜 AI 请求失败（HTTP ${response.status}）`); const text= s.optimizerProvider==='ollama'?data.response:data.choices?.[0]?.message?.content; if(typeof text!=='string') throw new Error('分镜 AI 没有返回文本');
  try{return parse(text);}catch{ const repair=`请修复下面内容为合法 JSON，只返回 JSON，不添加解释。必须符合：${schema}\n原始内容：${text}`; const repairBody=s.optimizerProvider==='gemini'?{contents:[{parts:[{text:repair}]}]}:s.optimizerProvider==='anthropic'?{model:s.optimizerModel,max_tokens:4000,system:'你是 JSON 修复器，只输出合法 JSON。',messages:[{role:'user',content:repair}]}:s.optimizerProvider==='ollama'?{model:s.optimizerModel,stream:false,prompt:repair}:{model:s.optimizerModel,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:'你是 JSON 修复器，只输出合法 JSON。'},{role:'user',content:repair}]}; const repairResponse=await fetch(endpoint(s.optimizerProvider,s.optimizerBaseUrl),{method:'POST',headers,body:JSON.stringify(repairBody),signal}); const repaired:any=await repairResponse.json().catch(()=>({})); const repairedText=s.optimizerProvider==='ollama'?repaired.response:s.optimizerProvider==='gemini'?repaired.candidates?.[0]?.content?.parts?.[0]?.text:s.optimizerProvider==='anthropic'?repaired.content?.[0]?.text:repaired.choices?.[0]?.message?.content; if(typeof repairedText!=='string')throw new Error('AI 返回不是合法 JSON，修复失败'); try{return parse(repairedText);}catch{throw new Error('AI 返回不是合法分镜 JSON');} }
}